INSERT INTO Users (name, email, occupation, newsletter, hash, createdAt, updatedAt) VALUES
('Alice Johnson', 'alice.johnson@example.com', 'Software Developer', true, 'abc123hash', NOW(), NOW()),
('Bob Smith', 'bob.smith@example.com', 'Data Analyst', false, 'def456hash', NOW(), NOW()),
('Charlie Brown', 'charlie.brown@example.com', 'Graphic Designer', true, 'ghi789hash', NOW(), NOW()),
('Diana White', 'diana.white@example.com', 'Project Manager', false, 'jkl012hash', NOW(), NOW()),
('Ethan Black', 'ethan.black@example.com', 'Web Developer', true, 'mno345hash', NOW(), NOW()),
('Fiona Green', 'fiona.green@example.com', 'Digital Marketer', false, 'pqr678hash', NOW(), NOW()),
('George Harris', 'george.harris@example.com', 'UX Designer', true, 'stu901hash', NOW(), NOW()),
('Hannah Lee', 'hannah.lee@example.com', 'IT Support', true, 'vwx234hash', NOW(), NOW()),
('Ian Clark', 'ian.clark@example.com', 'Network Engineer', false, 'yz123hash', NOW(), NOW()),
('Julia Turner', 'julia.turner@example.com', 'Technical Writer', true, 'abc456hash', NOW(), NOW()),
('Kevin Adams', 'kevin.adams@example.com', 'Database Administrator', false, 'def789hash', NOW(), NOW()),
('Laura Scott', 'laura.scott@example.com', 'Content Creator', true, 'ghi012hash', NOW(), NOW()),
('Mike Davis', 'mike.davis@example.com', 'System Administrator', false, 'jkl345hash', NOW(), NOW()),
('Nina Baker', 'nina.baker@example.com', 'DevOps Engineer', true, 'mno678hash', NOW(), NOW()),
('Oliver Hill', 'oliver.hill@example.com', 'Frontend Developer', true, 'pqr901hash', NOW(), NOW()),
('Paula Allen', 'paula.allen@example.com', 'Backend Developer', false, 'stu234hash', NOW(), NOW()),
('Quincy Wright', 'quincy.wright@example.com', 'Cloud Architect', true, 'vwx567hash', NOW(), NOW()),
('Rachel Young', 'rachel.young@example.com', 'Machine Learning Engineer', false, 'yz890hash', NOW(), NOW()),
('Sam Thompson', 'sam.thompson@example.com', 'Cybersecurity Specialist', true, 'abc123hash', NOW(), NOW()),
('Tina Walker', 'tina.walker@example.com', 'Game Developer', true, 'def456hash', NOW(), NOW());
